server:
  port: 8082

spring:
  application:
    name: loan-service
  config:
    import: "optional:configserver:"  # ✅ quotes fix the YAML parsing error

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
